global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'nestjs'
    basic_auth:
      username: prometheus
      password: your_secure_password_here
    static_configs:
      - targets: ['nestjs-app:3000']
    metrics_path: '/metrics'
    scheme: http
